### PR TITLE
hal: telink: Add Zephyr power management functionality for BLE unit

### PR DESCRIPTION
**Pull request by andriy-bilynskyy**
Original Telink BLE SDK provides power management functionality by itself.
This approach is not suitable for multi-thread functionality since OS kernel
and other threads has no information about sleep condition. So time based
entering sleep mode is replaced by OS delay. In that case kernel judge about
entering sleep mode instead of BLE controller thread.
Tested manually using TLSR9518ADK80D by running BLE samples.

### CODE REVIEW

**Review by andy-liu-telink — APPROVED** [review]

**Review by andy-liu-telink — APPROVED** [review]

**Review by andy-liu-telink — APPROVED** [review]

**Review by andy-liu-telink — APPROVED** [review]

**Comment by andy-liu-telink** [comment]
@cfriedt Could you help approve this PR?   Yura has left our group, and I am supposed to take care of PRs for this hal_telink repo. However, I have not yet found any button to approve this PR.

**Comment by cfriedt** [comment]
> @cfriedt Could you help approve this PR?   Yura has left our group, and I am supposed to take care of PRs for this hal_telink repo. However, I have not yet found any button to approve this PR.

@andy-liu-telink - you need to review the changed files and then there should be an approve option.

Does `k_sleep()` provide enough accuracy here? I would have thought it needed to be better.

**Review by s07641069 — APPROVED** [review]

**Review by s07641069 — APPROVED** [review]

**Review by andy-liu-telink — APPROVED** [review]
Approved.

**Comment by andriy-bilynskyy** [comment]
We have tick period equal to 1mS in order to achive suitable accuracy we reduce our sleep time by few mS which is defined in B91_BT_SLEEP_AJUSTMENT. So we always wake-up earlier and after that wait in active mode.

**Review by andy-liu-telink — APPROVED** [review]
@andy-liu-telink approved this pull request.

**Comment by andy-liu-telink** [comment]
@cfriedt 

I can see that I'm already a maintainer of this hal_telink. 
image

My problem still remains.  I still have not yet found any approve option even after I review all the changed files.
Do you know anyone that I can contact to help me with this problem?
Also,  could you help me approve this pull request if you have the right permission? Thanks.

**Review by cfriedt — APPROVED** [review]

**Review by stephanosio — CHANGES_REQUESTED** [review]
There needs to be an associated Zephyr-side PR before this can be merged.

**Comment by andriy-bilynskyy** [comment]
> There needs to be an associated Zephyr-side PR before this can be merged.

**Comment by andriy-bilynskyy** [comment]
@stephanosio
> There needs to be an associated Zephyr-side PR before this can be merged.
Zephyr-side PR requires changes in west.yml with revision of this PR merged.
Which revision and remote should be set west.yml before applying this PR?
Current remote and revision of merged brunch?

**Comment by stephanosio** [comment]
> Which revision and remote should be set west.yml before applying this PR?
> Current remote and revision of merged brunch?

Please review https://docs.zephyrproject.org/latest/develop/modules.html#process-for-submitting-changes-to-existing-modules.

**Comment by andriy-bilynskyy** [comment]
Created PR to zephyr repo
https://github.com/zephyrproject-rtos/zephyr/pull/48262

**Review by stephanosio — APPROVED** [review]

**Pull request merged**
